apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-volv-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
